### ISSUE TITLE
1.3.2: Server muted when responding to whereto

### ISSUE THREAD

**Issue by Iambb-AC** [patri0t86/ACManager#20]
Reefcull has a spam limiter. When responding to Whereto requests, I am server muted after the first 7 portal destinations.

**Comment by patri0t86** [comment]
I'll have to look into a message buffer to try to handle this dynamically, or give a "brief output" option so that the "whereto" response is in fewer messages. 

Anyone have thoughts on any better options?

**Comment by Iambb-AC** [comment]
Even if you did Primary/Secondary on one line, it would still only be 7 of 11 needed lines per account. I suggest adding an adjustable delay setting, maybe starting at 500 ms that will pause between messages. On servers where there is no spam limit, the user could just set it to zero.

**Comment by patri0t86** [comment]
Fixed in version 1.4.0!
