### ISSUE TITLE
1.3.2: Cannot update primary/secondary destinations unless logged on that character

### ISSUE THREAD

**Issue by Iambb-AC** [patri0t86/ACManager#21]
You can select other characters on the account, but updates to primary or secondary portal info is not saved unless you are logged on the character you are editing.

**Comment by patri0t86** [comment]
This was an unintended side effect from the last update. The entire settings file/folder structure is going to be reworked on the next update and should alleviate all of these issues.

**Comment by patri0t86** [comment]
The latest commit should take care of this, settings are now separated by account/server. The new DLLs are out for testing.

**Comment by patri0t86** [comment]
Fixed in version 1.3.3.
