### ISSUE TITLE
Character log in/out loop caused when requested portal is on another account

### ISSUE THREAD

**Issue by Iambb-AC** [patri0t86/ACManager#22]
When character on account 1 is whispered requesting a portal on account 2, account 1 tries to log off and switch to the account 2 character. Causing a relog loop.

**Comment by patri0t86** [comment]
This is related to the settings file issue mentioned in my comment to issue #21. This should be rectified in the next patch.

**Comment by patri0t86** [comment]
Fixed in version 1.3.3.
