### ISSUE TITLE
Persistent Exp Tracker Checkbox

### ISSUE THREAD

**Issue by GuruBaronTX** [patri0t86/ACManager#28]
To use the Exp Tracker, every time you need to open AC Manager and then turn on the Exp Tracker then turn off AC Manager and then open the Exp Tracker.

**Comment by patri0t86** [comment]
Looking into adding GUI persistence settings in a coming update, this has been requested before and is now properly tracked.

**Comment by patri0t86** [comment]
Persistent GUI changes are now saved to file in the latest commit. Will be out in the next release!
