### ISSUE TITLE
Low Component Announcement

### ISSUE THREAD

**Issue by GuruBaronTX** [patri0t86/ACManager#29]
For example the portal bot is running low on tapers or scarabs (or even gems?) it can add an additional spam message saying something to that affect. Probably should be settable numbers like 500 tapers or 10 scarabs.

**Comment by patri0t86** [comment]
The bot now checks components on each spell cast to ensure it has the components for the spell.

In addition, it now keeps track of the current component level. You can set variable thresholds per scarab and all other components. This message is spammed on advertisement interval and each time casting is starting.

Will be included in next release.
