### ISSUE TITLE
Self Buffing breaks buffing.

### ISSUE THREAD

**Issue by first2di3** [patri0t86/ACManager#38]
You and I worked through this in discord, just putting the bug on here for future reference.

**Comment by patri0t86** [comment]
For context: When the bot was not fully self-buffed, it failed self-buffing cycles and buffing other cycles repeatedly until finally the bot was able to buff itself, then it worked without issue. Will need to perform more testing to discover what is breaking this feature. When failing, creature enchantment was 335 base, 395 buffed.

**Comment by patri0t86** [comment]
New release https://github.com/patri0t86/ACManager/releases/tag/v3.1.0-rc1 may fix this, will need more testing...

**Comment by patri0t86** [comment]
Fixed in the latest release found: https://github.com/patri0t86/ACManager/releases/tag/v3.1.1.1
