### ISSUE TITLE
Feature Request: Bots respond to allegiance chat.

### ISSUE THREAD

**Issue by first2di3** [patri0t86/ACManager#39]
We would like to see a toggleable feature to allow the portal (and buff) bots to react to Allegiance (/a) chat, so that if we are on our way to the mansion or if someone asks how to get somewhere, we can tell the bots to open a portal at the mansion without having to figure out which bot is currently logged on.

This would also allow portal bots to be placed anywhere in the world and react to a request to log in a portal bot no matter which of the bots are logged in.

**Comment by patri0t86** [comment]
I don't see any issue with this feature. My planned implementation will be just like with the local chat command feature: it is togglable as a global bot configuration.

Interesting use of the bot, never thought to use it that way!

**Comment by patri0t86** [comment]
This is now implemented and will be in the next release!
